package uk.gov.moj.cpp.staging.command.api.accesscontrol;
import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

import uk.gov.moj.cpp.staging.prosecutors.accesscontrol.RuleConstants


global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for updating a police system id for oi"
  when
    $outcome: Outcome();
    $action: Action(name == "stagingprosecutorsspi.command.spi-oi-update-police-system-id");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getSystemUsers()))
  then
    $outcome.setSuccess(true);
end