package uk.gov.moj.cpp.staging.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

import uk.gov.moj.cpp.staging.prosecutors.accesscontrol.RuleConstants


global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for resending a cpp message"
  when
    $outcome: Outcome();
    $action: Action(name == "hmcts.cjs.resend-message");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getSystemUsers()))
  then
    $outcome.setSuccess(true);
end