cpp.activiti.datasource.name=java:/DS.stagingprosecutorsspi
cpp.activiti.databaseSchemaUpdate=true
cpp.activiti.transactionsExternallyManaged=true
cpp.activiti.jobExecutorActivate=true
cpp.activiti.asyncExecutorEnabled=true
cpp.activiti.asyncExecutorActivate=true
cpp.activiti.createDiagramOnDeploy=true
